BowlingLeague/Models/Bowler.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BowlingLeague.Models
{
    public class Bowler
    {
        [Key]
        [Required]
        public int BowlerId { get; set; }
        public string BowlerLastName { get; set; }
        public string BowlerFirstName { get; set; }
        public string BowlerMiddleInit { get; set; }
        public string BowlerAddress { get; set; }
        public string BowlerCity { get; set; }
        public string BowlerState { get; set; }
        public string BowlerZip { get; set; }
        public string BowlerPhoneNumber { get; set; }

        // Foreign Key Relationship
        public int TeamId { get; set; }
        public Team Team { get; set; }
    }
}

BowlingLeague/Models/BowlersDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BowlingLeague.Models
{
    public class BowlersDbContext : DbContext
    {
        public BowlersDbContext(DbContextOptions<BowlersDbContext> options) : base (options)
        {
        }

        public DbSet<Bowler> Bowlers { get; set; }
        public DbSet<Team> Teams { get; set; }
    }
}

BowlingLeague/Models/EFBowlersRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BowlingLeague.Models
{
    public class EFBowlersRepository : IBowlersRepository
    {
        private BowlersDbContext _context { get; set; }

        public EFBowlersRepository(BowlersDbContext temp)
        {
            _context = temp;
        }

        public IQueryable<Bowler> Bowlers => _context.Bowlers;
        public IQueryable<Team> Teams => _context.Teams;

        public void SaveBowler(Bowler b)
        {
            _context.Update(b);
            _context.SaveChanges();
        }

        public void CreateBowler(Bowler b)
        {
            _context.Add(b);
            _context.SaveChanges();
        }

        public void DeleteBowler(Bowler b)
        {
            _context.Remove(b);
            _context.SaveChanges();
        }
    }
}

BowlingLeague/Models/IBowlersRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BowlingLeague.Models
{
    public interface IBowlersRepository
    {
        IQueryable<Bowler> Bowlers { get; }
        IQueryable<Team> Teams { get; }

        //Edit
        public void SaveBowler(Bowler b);
        //Create
        public void CreateBowler(Bowler b);
        //Delete
        public void DeleteBowler(Bowler b);
    }
}

BowlingLeague/Models/Team.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BowlingLeague.Models
{
    public class Team
    {
        [Key]
        [Required]
        public int TeamId { get; set; }
        public string TeamName { get; set; }
        public int CaptainId { get; set; }
    }
}

BowlingLeague/Components/TeamsViewComponent.cs
using BowlingLeague.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BowlingLeague.Components
{
    public class TeamsViewComponent : ViewComponent
    {
        private IBowlersRepository _repo { get; set; }

        public TeamsViewComponent (IBowlersRepository temp)
        {
            _repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedTeam = RouteData?.Values["team"];

            var teams = _repo.Bowlers
                .Include(x => x.Team)
                .Select(x => x.Team.TeamName)
                .Distinct()
                .OrderBy(x => x);

            return View(teams);
        }
    }
}

BowlingLeague/Controllers/HomeController.cs
using BowlingLeague.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BowlingLeague.Controllers
{
    public class HomeController : Controller
    {
        private IBowlersRepository _repo { get; set; }

        // Constructor
        public HomeController(IBowlersRepository temp)
        {
            _repo = temp;
        }

        public IActionResult Index(string team)
        {
            ViewBag.TeamTitle = team;

            var x = _repo.Bowlers
                .Include(x => x.Team)
                .Where(x => x.Team.TeamName == team || team == null)
                .ToList();

            return View(x);
        }

        [HttpGet]
        public IActionResult EditForm(int bowler)
        {
            ViewBag.Teams = _repo.Teams.ToList();

            var x = _repo.Bowlers
                .Include(x => x.Team)
                .Single(x => x.BowlerId == bowler);

            return View("EditForm", x);
        }

        [HttpPost]
        public IActionResult EditForm(Bowler b)
        {
            _repo.SaveBowler(b);
            
            return RedirectToAction("Index");
        }
        
        [HttpGet]
        public IActionResult AddForm()
        {
            ViewBag.Teams = _repo.Teams.ToList();
            ViewBag.IDs = _repo.Bowlers.Max(x => x.BowlerId) + 1;

            return View(new Bowler());
        }

        [HttpPost]
        public IActionResult AddForm(Bowler b)
        {
            _repo.CreateBowler(b);

            return RedirectToAction("Index");
        }

        public IActionResult DeleteBowler(int bowler)
        {
            Bowler b = _repo.Bowlers
                .Include(x => x.Team)
                .Single(x => x.BowlerId == bowler);

            _repo.DeleteBowler(b);

            return RedirectToAction("Index");
        }
    }
}

BowlingLeague/Views/Home/AddForm.cshtml
@{
}

@model Bowler

<div class="row">
    <div class="col-1"></div>

    <div class="col-11">
        <h1>Add Bowler Here</h1>

        <form method="post" asp-action="AddForm">

            <input type="hidden" asp-for="BowlerId" value="@ViewBag.IDs" />

            <div class="form-group">
                <label asp-for="BowlerFirstName">First Name:</label>
                <input class="form-control" asp-for="BowlerFirstName" />
            </div>

            <div class="form-group">
                <label asp-for="BowlerMiddleInit">Middle Initial:</label>
                <input class="form-control" asp-for="BowlerMiddleInit" />
            </div>

            <div class="form-group">
                <label asp-for="BowlerLastName">Last Name:</label>
                <input class="form-control" asp-for="BowlerLastName" />
            </div>

            <div class="form-group">
                <label asp-for="BowlerAddress">Address:</label>
                <input class="form-control" asp-for="BowlerAddress" />
            </div>

            <div class="form-group">
                <label asp-for="BowlerCity">City:</label>
                <input class="form-control" asp-for="BowlerCity" />
            </div>

            <div class="form-group">
                <label asp-for="BowlerState">State:</label>
                <input class="form-control" asp-for="BowlerState" />
            </div>

            <div class="form-group">
                <label asp-for="BowlerZip">Zip:</label>
                <input class="form-control" asp-for="BowlerZip" />
            </div>

            <div class="form-group">
                <label asp-for="BowlerPhoneNumber">Phone Number:</label>
                <input class="form-control" asp-for="BowlerPhoneNumber" />
            </div>

            <div class="form-group">
                <label asp-for="TeamId">Team:</label>
                <select class="form-control" asp-for="TeamId">
                    @foreach (Team b in ViewBag.Teams)
                    {
                        <option value="@b.TeamId">@b.TeamName</option>
                    }
                </select>
            </div>

            <button type="submit" class="btn btn-lg btn-primary">Save</button>
        </form>
    </div>

</div>

BowlingLeague/Views/Home/EditForm.cshtml
@{
}

@model Bowler

<div class="row">
    <div class="col-1"></div>

    <div class="col-11">
        <h1>Edit Bowler Here</h1>

        <form method="post" asp-action="EditForm">

            <input type="hidden" value="@Model.BowlerId" asp-for="BowlerId"/>

            <div class="form-group">
                <label asp-for="BowlerFirstName">First Name:</label>
                <input class="form-control" asp-for="BowlerFirstName" value="@Model.BowlerFirstName" />
            </div>

            <div class="form-group">
                <label asp-for="BowlerMiddleInit">Middle Initial:</label>
                <input class="form-control" asp-for="BowlerMiddleInit" value="@Model.BowlerMiddleInit" />
            </div>

            <div class="form-group">
                <label asp-for="BowlerLastName">Last Name:</label>
                <input class="form-control" asp-for="BowlerLastName" value="@Model.BowlerLastName" />
            </div>

            <div class="form-group">
                <label asp-for="BowlerAddress">Address:</label>
                <input class="form-control" asp-for="BowlerAddress" value="@Model.BowlerAddress" />
            </div>

            <div class="form-group">
                <label asp-for="BowlerCity">City:</label>
                <input class="form-control" asp-for="BowlerCity" value="@Model.BowlerCity" />
            </div>

            <div class="form-group">
                <label asp-for="BowlerState">State:</label>
                <input class="form-control" asp-for="BowlerState" value="@Model.BowlerState" />
            </div>

            <div class="form-group">
                <label asp-for="BowlerZip">Zip:</label>
                <input class="form-control" asp-for="BowlerZip" value="@Model.BowlerZip" />
            </div>

            <div class="form-group">
                <label asp-for="BowlerPhoneNumber">Phone Number:</label>
                <input class="form-control" asp-for="BowlerPhoneNumber" value="@Model.BowlerPhoneNumber" />
            </div>

            <div class="form-group">
                <label asp-for="TeamId">Team:</label>
                <select class="form-control" asp-for="TeamId" value="@Model.TeamId">
                    @foreach (Team b in ViewBag.Teams)
                    {
                        <option value="@b.TeamId">@b.TeamName</option>
                    }
                </select>
            </div>

            <button type="submit" class="btn btn-lg btn-primary">Save</button>
        </form>
    </div>

</div>

BowlingLeague/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model List<Bowler>

<div class="row m-1 p-1">
    <div id="teams" class="col-2">
        <vc:teams></vc:teams>
    </div>
    <div class="col-10">
        <h1 class="bg-secondary text-center text-white rounded-pill">Welcome to the Washington Bowling League!</h1>
        <br />
        @if (ViewBag.TeamTitle != null)
        {
            <h2 class="text-black p-2">Team: <b>@ViewBag.TeamTitle</b></h2>
        }
        else
        {
            <h2 class="text-black p-2"><b>All Bowlers</b></h2>
        }


        @foreach (Bowler b in Model)
        {
            <partial name="BowlerSummary" model="b" />
        }
    </div>
</div>

BowlingLeague/Views/Shared/BowlerSummary.cshtml
@{
}

@model Bowler

<div class="card card-outline-primary m-2 p-1">
    <div class="bg-info p-1 rounded">
        <h3 class="text-white">@Model.BowlerFirstName @Model.BowlerMiddleInit @Model.BowlerLastName</h3>

        <span class="badge bg-light">
            Team: <b>@Model.Team.TeamName</b>
        </span>
    </div>
    <br />
    <ul>
        <li>Address: @Model.BowlerAddress</li>
        <li>City: @Model.BowlerCity</li>
        <li>State: @Model.BowlerState</li>
        <li>Zip: @Model.BowlerZip</li>
        <li>Phone Number: @Model.BowlerPhoneNumber</li>
    </ul>
 
    <div class="form-row p-1">

        <a class="btn btn-primary btn-sm text-white" asp-route-bowler="@Model.BowlerId" asp-controller="Home" asp-action="EditForm">Edit</a>
        &nbsp;
        <a class="btn btn-danger btn-sm text-white" asp-route-bowler="@Model.BowlerId" asp-controller="Home" asp-action="DeleteBowler">Delete</a>
    </div>
</div>

BowlingLeague/Views/Shared/Components/Teams/Default.cshtml
@{
}

@model IEnumerable<string>

<div class="d-grid gap-2">
    <a asp-controller="Home" asp-action="Index" asp-route-team="" class="btn btn-block btn-outline-secondary">All Bowlers</a>

    @foreach (string t in Model)
    {
        <a asp-controller="Home" asp-action="Index" asp-route-team="@t" 
           class="btn btn-block @(ViewBag.SelectedTeam == t ? "btn-dark" : "btn-outline-secondary")">@t</a>
    }
</div>

BowlingLeague/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand" >
                    <a class="nav-link text-white" asp-controller="Home" asp-action="Index" asp-route-team="">Home</a>
                </div>
                <div class="navbar-brand float-end">
                    <a class="nav-link text-white btn btn-secondary" asp-controller="Home" asp-action="AddForm">Sign Up</a>
                </div>
            </div>
        </div>
    </div>


    <div class="row m-1 p-1">

        <div class="col-10">
            <div>
                @RenderBody()
            </div>
        </div>

        <div class="col-2">
            <p>Do you think you are good? Add yourself to the league with the link above!</p>
            <img class="img-fluid" src="~/img/bowling.jpg" />
        </div>

    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>